version: "3"

tasks:
  dev-backend:
    desc: Run backend in watch mode.
    cmds:
      - dotnet watch --project src/Enmarcha.Backend/Enmarcha.Backend.csproj

  dev-frontend:
    desc: Run frontend development server.
    cmds:
      - npm run dev --prefix src/frontend

  build-backend:
    desc: Publish backend in Release mode.
    cmds:
      - dotnet publish -c Release -o ./dist/backend src/Enmarcha.Backend/Enmarcha.Backend.csproj

  build-backend-prod:
    desc: Publish backend for Prod server
    cmds:
      - dotnet publish -c Release -r linux-arm64 --self-contained false src/Enmarcha.Backend/Enmarcha.Backend.csproj -o dist/backend

  build-frontend:
    desc: Build frontend bundle.
    cmds:
      - npm run build --prefix src/frontend
      - mkdir dist/frontend
      - cp -r src/frontend/build/client/* dist/frontend

  format:
    desc: Format backend solution.
    cmds:
      - dotnet format --verbosity diagnostic src/Enmarcha.Backend/Enmarcha.Backend.csproj
      - npx prettier --write "src/frontend/**/*.{ts,tsx,css}"
